import { Theme } from "../theme.slint";

export component Clock inherits Rectangle {
    in property <string> time: "00:00";
    in property <string> date: "01 Jan, Monday";
    in property <length> time-font-size: 34px;
    height: 60px;

    VerticalLayout {
        spacing: 2px;
        alignment: start;

        Text {
            text: root.time;
            color: Theme.color4;
            font-size: root.time-font-size;
            font-family: "Monocraft";
            horizontal-alignment: left;
        }

        Text {
            text: root.date;
            color: Theme.color4.with-alpha(0.6);
            font-size: 14px;
            font-family: "Monocraft";
            horizontal-alignment: left;
        }
    }
}