import { Theme } from "../theme.slint";
export component MoonWithCloudPosition inherits Rectangle {
    in property <length> pixel-size: 2px;
    width: 6 * pixel-size;
    height: 8 * pixel-size;

    property <[{x: int, y: int}]> pixels: [
        {x: 1, y: 0}, {x: 2, y: 0}, {x: 3, y: 0},
        {x: 1, y: 1}, {x: 4, y: 1},
        {x: 2, y: 2}, {x: 5, y: 2},
        {x: 2, y: 3}, {x: 5, y: 3},
        {x: 1, y: 4}, {x: 5, y: 4},
        {x: 0, y: 5}, {x: 5, y: 5},
        {x: 4, y: 6},
        {x: 2, y: 7}, {x: 3, y: 7},
    ];

    for p in pixels: Rectangle {
        x: p.x * pixel-size;
        y: p.y * pixel-size;
        width: pixel-size;
        height: pixel-size;
        background:Theme.foreground.with-alpha(0.8);
    }
}