export global Theme {
    in-out property <bool> _dirty: false;

    in-out property <brush> background: #1e1e2e;
    in-out property <brush> foreground: #cdd6f4;

    in-out property <brush> color0: #45475a;
    in-out property <brush> color1: #f38ba8;
    in-out property <brush> color2: #a6e3a1;
    in-out property <brush> color3: #f9e2af;
    in-out property <brush> color4: #89b4fa;
    in-out property <brush> color5: #f5c2e7;
    in-out property <brush> color6: #94e2d5;
    in-out property <brush> color7: #bac2de;
    in-out property <brush> color8: #585b70;
    in-out property <brush> color9: #f38ba8;
    in-out property <brush> color10: #a6e3a1;
    in-out property <brush> color11: #f9e2af;
    in-out property <brush> color12: #89b4fa;
    in-out property <brush> color13: #f5c2e7;
    in-out property <brush> color14: #94e2d5;
    in-out property <brush> color15: #a6adc8;
}
